version: '3'

volumes:
  mongodb_data:
    driver: local


services:
  mongodb:
    image: mongo:4.2.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
